import create from 'zustand';
import { persist } from 'zustand/middleware';
import { CONTENT_TYPE } from '../constant';

export const userStore = create(persist(
    set => ({
        id: '',
        setID: (id) => set({ id }),
        username: '',
        setUsername: (username) => set({ username }),
        comicNotifications: [],
        setComicNotifications: (comicNotifications) => set({ comicNotifications }),
        storyNotifications: [],
        setStoryNotifications: (storyNotifications) => set({ storyNotifications }),
        followers: [],
        setFollowers: (followers) => set({ followers }),
        followingUsers: [],
        setFollowingUsers: (followingUsers) => set({ followingUsers }),
        followingComics: [],
        setFollowingComics: (followingComics) => set({ followingComics }),
        followingStories: [],
        setFollowingStories: (followingStories) => set({ followingStories }),
        isLoggedIn: false,
        setIsLoggedIn: (isLoggedIn) => set({ isLoggedIn }),
        isAdmin: false,
        setIsAdmin: (isAdmin) => set({ isAdmin }),
        siteMode: CONTENT_TYPE.COMIC,
        setSiteMode: (siteMode) => set({ siteMode }),
        likedComics: [],
        setLikedComics: (likedComics) => set({ likedComics }),
        dislikedComics: [],
        setDislikedComics: (dislikedComics) => set({ dislikedComics }),
        likedPages: [],
        setLikedPages: (likedPages) => set({ likedPages }),
        dislikedPages: [],
        setDislikedPages: (dislikedPages) => set({ dislikedPages }),
        likedStories: [],
        setLikedStories: (likedStories) => set({ likedStories }),
        dislikedStories: [],
        setDislikedStories: (dislikedStories) => set({ dislikedStories }),
        likedChapters: [],
        setLikedChapters: (likedChapters) => set({ likedChapters }),
        dislikedChapters: [],
        setDislikedChapters: (dislikedChapters) => set({ dislikedChapters }),
        login: (id, username, likedComics, dislikedComics, likedPages, dislikedPages, likedStories, dislikedStories, likedChapters, dislikedChapters, isAdmin) => set({ id, username, likedComics, dislikedComics, likedPages, dislikedPages, likedStories, dislikedStories, likedChapters, dislikedChapters, isLoggedIn: true, isAdmin }),
        resetStore: () => set({ id: '', username: '', comicNotifications: [], storyNotifications: [], followers: [], followingUsers: [], followingComics: [], followingStories: [], ownComics: [], ownStories: [], isLoggedIn: false, isAdmin: false }),
    }),
    {
        name: 'user-storage',
    },
));
